version: "3.3"

services:
    mysql:
        build: 
            context: ./db
        container_name: mysql
        restart: always
        image: mysql
        volumes: 
          - dbdata:/var/lib/mysql
          #- ./db:/docker-entrypoint-initdb.d/:ro
          #- ./db:/docker-entrypoint-initdb.d/init.sql
        environment:
          MYSQL_ROOT_PASSWORD: 'BDATpassword'
          MYSQL_DATABASE: 'BDAT_FE_simulations'
          MYSQL_USER: 'UserBDAT'
          MYSQL_PASSWORD: 'BDATpassword'
        ports:
            - '3306:3306'

    backend:
        depends_on:
            - mysql
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        restart: always
        ports:
            - '3000:3000'

    frontend:
        depends_on:
          - mysql
          - backend
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        container_name: frontend-react
        stdin_open: true
        ports:
            - '3001:3001'
        environment:
            CHOKIDAR_USEPOLLING: "true"
        
volumes: 
    dbdata: